spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
